### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by chtenb** [coddingtonbear/taskwarrior-capsules#3]
Hi

It's 2020, can we move toward being python 3 compatible, or is there a compelling reason not to?

```
$ tw
Traceback (most recent call last):
  File "/home/chiel/.local/bin/tw", line 8, in <module>
    sys.exit(main())
  File "/home/chiel/.local/lib/python3.8/site-packages/taskwarrior_capsules/cmdline.py", line 59, in main
    commands = get_initialized_installed_capsules(
  File "/home/chiel/.local/lib/python3.8/site-packages/taskwarrior_capsules/cmdline.py", line 41, in get_initialized_installed_capsules
    capsules = get_installed_capsules(variant)
  File "/home/chiel/.local/lib/python3.8/site-packages/taskwarrior_capsules/cmdline.py", line 26, in get_installed_capsules
    loaded_class = entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/chiel/.local/lib/python3.8/site-packages/taskwarrior_capsules/commands/main.py", line 27
    print "{t.bold}{t.blue}{headline}{t.normal}:".format(
          ^
SyntaxError: invalid syntax
```

**Comment by mokrunka** [comment]
I submitted a PR to (hopefully) fix this issue. Is anyone still maintaining this code? I don't actually use this software, but I was looking for code to contribute to, and jumped in to help fix it.

**Comment by chtenb** [comment]
@coddingtonbear could this be merged and a new version released on pip?

**Comment by mokrunka** [comment]
Bump. What do you think, @coddingtonbear?

**Comment by coddingtonbear** [comment]
Oh my; I... forgot I even still had this project.  Do one of you want to take over ownership of this -- I'd be glad to give somebody maintainership.

**Comment by mokrunka** [comment]
Thank you for replying! I'll be honest, I'm not a professional coder, and I hopped in here to try practicing github, and python to help you fix one of the open issues I thought I could tackle. I'm happy to take ownership of it, but it would be a first for me! Is there anything special I need to do? Any guidance or advice? :). Thanks @coddingtonbear!

**Comment by coddingtonbear** [comment]
I've just added you as a collaborator so you once you accept that, you can do things like merge PRs and whatnot.  If you let me know what your name is on PyPI (or create an account there if you haven't -> https://pypi.org/) I'll add you as an owner there.

I _tried_ to transfer the repository to you directly, but you already have a fork, and that would need to be deleted before Github would be able to do the transfer.  You don't want to do that yet, though, because then you'd lose your PR, I think?  Once you've had a chance to merge your PR, I can do the full transfer.

After that, we just need to bump the version number and push a new package to PyPI.  I don't know how much experience you have with that sort of thing, though, so feel free to message me on matrix (@coddingtonbear:matrix.org) or freenode (coddingtonbear) if you need a hand.

**Comment by mokrunka** [comment]
Great! Thank you. I accepted the invite to collaborate. I've also merged the PR and closed the associated issue. Finally, I've deleted my fork, so I *think* you should be able to add me as the owner.

I have not used PyPI yet, but I am excited to try it out. I've also not used matrix or freenode, but I'll sign up so that I can message you. I'll need some help (probably) understanding how to bump the version up and do the package thing. Thanks a bunch for the help!
